### ISSUE TITLE
An error message appears when i run app.js

### ISSUE THREAD

**Issue by Bdbmzwsc** [SkyWorldStudio/MSS_3-Web-Production#1]
just run command
`node app.js`

error message
```
[MSS 3] Powered By SkyWorldStudio
[MSS 3] Version: undefined
[MSS 3] Init Starting
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'i18next'
Require stack:
- /Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 805 (/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js:1:5699)
    at o (/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js:1:6963)
    at 95 (/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js:1:4849)
    at o (/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js:1:6963)
    at 326 (/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js:1:5439)
    at o (/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js:1:6963) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/bdbmzwsc/Downloads/MSS_3-Web-Production-1.0.1/app.js' ]
}

Node.js v19.0.0
```
Os: MacOS Monterey 12.6

**Comment by Stardito** [comment]
Thanks for your feedback! We lost the steps of installation dependency in the project. This problem will be fixed in the next version
