### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by David-Xian66** [SkyWorldStudio/MSS_3-Web-Production#2]
在执行`node app.js`命令后报错：
```
        _   _         _           _              _          
       /\_\/\_\ _    / /\        / /\          /\ \         
      / / / / //\_\ / /  \      / /  \        /  \ \        
     /\ \/ \ \/ / // / /\ \__  / / /\ \__    / /\ \ \       
    /  \____\__/ // / /\ \___\/ / /\ \___\  / / /\ \ \      
   / /\/________/ \ \ \ \/___/\ \ \ \/___/  \/_//_\ \ \     
  / / /\/_// / /   \ \ \       \ \ \          __\___ \ \    
 / / /    / / /_    \ \ \  _    \ \ \        / /\   \ \ \   
/ / /    / / //_/\__/ / / /_/\__/ / /       / /_/____\ \ \  
\/_/    / / / \ \/___/ /  \ \/___/ /       /__________\ \ \ 
        \/_/   \_____\/    \_____\/        _____________\/ 

[MSS 3] Powered By SkyWorldStudio
[MSS 3] Version: 1.0.4
[MSS 3] Init Starting
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'i18next'
Require stack:
- /Users/xyj/.npm/MSS_3-Web-Production/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 805 (/Users/xyj/.npm/MSS_3-Web-Production/app.js:1:13529)
    at s (/Users/xyj/.npm/MSS_3-Web-Production/app.js:1:15307)
    at 95 (/Users/xyj/.npm/MSS_3-Web-Production/app.js:1:5864)
    at s (/Users/xyj/.npm/MSS_3-Web-Production/app.js:1:15307)
    at 326 (/Users/xyj/.npm/MSS_3-Web-Production/app.js:1:13171)
    at s (/Users/xyj/.npm/MSS_3-Web-Production/app.js:1:15307) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/xyj/.npm/MSS_3-Web-Production/app.js' ]
}

Node.js v19.0.0
```

**Comment by Stardito** [comment]
这个 Bug 目前已被修复，感谢您的反馈！
